FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

# Install Python for simple HTTP server
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends python3
